version: "3.8"

services:
  node-app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=production

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: textMe
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql
    command: --init-file /docker-entrypoint-initdb.d/1.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: writable/db_data
      o: bind
